name: Build and Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint and Build (MacOS)
        run: |
          cd Team15/Code15
          mkdir cmake-build
          cd cmake-build
          brew install cmake
          brew install llvm
          echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.bashrc
          cmake ../
          cmake --build ./ --target unit-testing --config Release
          cmake --build ./ --target integration --config Release
          cmake --build ./ --target autotester --config Release
      - name: Cache (MacOS)
        uses: actions/cache@v2
        with:
          path: |
            Team15/Code15/cmake-build/src/autotester
          key: macos-autotester

  test-macos:
    needs: build-macos
    runs-on: macos-latest
    strategy:
      matrix:
        tests:
          - { source: source-assign.txt, query: query-assign.txt, output: assign.xml }
          - { source: source-calls.txt, query: query-calls.txt, output: calls.xml }
          - { source: source-follows.txt, query: query-follows.txt, output: follows.xml }
          - { source: source-general.txt, query: query-general.txt, output: general.xml }
          - { source: source-ifwhile.txt, query: query-ifwhile.txt, output: ifwhile.xml }
          - { source: source-parent.txt, query: query-parent.txt, output: parent.xml }
          - { source: source-usesmodifies.txt, query: query-usesmodifies.txt, output: usesmodifies.xml }

    steps:
      - uses: actions/checkout@v2
      - name: Restore (MacOS)
        uses: actions/cache@v2
        with:
          path: |
            Team15/Code15/cmake-build/src/autotester
          key: macos-autotester
      - name: Test (MacOS)
        run: |
          cd $GITHUB_WORKSPACE 
          Team15/Code15/cmake-build/src/autotester/autotester Team15/Tests15/${{ matrix.tests.source }} Team15/Tests15/${{ matrix.tests.query }} Team15/Code15/tests/${{ matrix.tests.output }}
          
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Linter (Windows)'
        shell: bash
        run: |
          $downloadUrl = "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/LLVM-15.0.7.win64.exe"
          Invoke-WebRequest $downloadUrl -OutFile LLVM.exe
          Start-Process -Wait -FilePath .\LLVM.exe -ArgumentList '/verysilent'
          echo "::add-path::C:\Program Files\LLVM\bin"
      - name: Build (Windows)
        shell: bash
        run: |
          cd Team15/Code15
          mkdir cmake-build
          cd cmake-build
          choco install -y cmake
          cmake ..
          cmake --build . --target unit-testing --config Release
          cmake --build . --target integration-testing --config Release
          cmake --build . --target autotester --config Release
      - name: Cache (Windows)
        uses: actions/cache@v2
        with:
          path: |
            Team15/Code15/cmake-build/src/autotester/Release/
          key: windows-autotester

  test-windows:
    needs: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        tests:
          - { source: source-assign.txt, query: query-assign.txt, output: assign.xml }
          - { source: source-calls.txt, query: query-calls.txt, output: calls.xml }
          - { source: source-follows.txt, query: query-follows.txt, output: follows.xml }
          - { source: source-general.txt, query: query-general.txt, output: general.xml }
          - { source: source-ifwhile.txt, query: query-ifwhile.txt, output: ifwhile.xml }
          - { source: source-parent.txt, query: query-parent.txt, output: parent.xml }
          - { source: source-usesmodifies.txt, query: query-usesmodifies.txt, output: usesmodifies.xml }

    steps:
      - uses: actions/checkout@v2
      - name: Restore (Windows)
        uses: actions/cache@v2
        with:
          path: |
            Team15/Code15/cmake-build/src/autotester/Release/
          key: windows-autotester
      - name: Test (Windows)
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./Team15/Code15/cmake-build/src/autotester/Release/autotester.exe ./Team15/Tests15/${{ matrix.tests.source }} ./Team15/Tests15/${{ matrix.tests.query }} ./Team15/Code15/tests/${{ matrix.tests.output }}
